//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avelango.Resources.Locations.En {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Countries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Countries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Avelango.Resources.Locations.En.Countries", typeof(Countries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andorra.
        /// </summary>
        public static string AD {
            get {
                return ResourceManager.GetString("AD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albania.
        /// </summary>
        public static string AL {
            get {
                return ResourceManager.GetString("AL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armenia.
        /// </summary>
        public static string AM {
            get {
                return ResourceManager.GetString("AM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Austria.
        /// </summary>
        public static string AT {
            get {
                return ResourceManager.GetString("AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azerbaijan.
        /// </summary>
        public static string AZ {
            get {
                return ResourceManager.GetString("AZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosnia and Herzegovina.
        /// </summary>
        public static string BA {
            get {
                return ResourceManager.GetString("BA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belgium.
        /// </summary>
        public static string BE {
            get {
                return ResourceManager.GetString("BE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulgaria.
        /// </summary>
        public static string BG {
            get {
                return ResourceManager.GetString("BG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belarus.
        /// </summary>
        public static string BY {
            get {
                return ResourceManager.GetString("BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switzerland.
        /// </summary>
        public static string CH {
            get {
                return ResourceManager.GetString("CH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech Republic.
        /// </summary>
        public static string CZ {
            get {
                return ResourceManager.GetString("CZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Germany.
        /// </summary>
        public static string DE {
            get {
                return ResourceManager.GetString("DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denmark.
        /// </summary>
        public static string DK {
            get {
                return ResourceManager.GetString("DK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estonia.
        /// </summary>
        public static string EE {
            get {
                return ResourceManager.GetString("EE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spain.
        /// </summary>
        public static string ES {
            get {
                return ResourceManager.GetString("ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finland.
        /// </summary>
        public static string FI {
            get {
                return ResourceManager.GetString("FI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to France.
        /// </summary>
        public static string FR {
            get {
                return ResourceManager.GetString("FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United Kingdom.
        /// </summary>
        public static string GB {
            get {
                return ResourceManager.GetString("GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Georgia.
        /// </summary>
        public static string GE {
            get {
                return ResourceManager.GetString("GE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greece.
        /// </summary>
        public static string GR {
            get {
                return ResourceManager.GetString("GR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatia.
        /// </summary>
        public static string HR {
            get {
                return ResourceManager.GetString("HR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hungary.
        /// </summary>
        public static string HU {
            get {
                return ResourceManager.GetString("HU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ireland.
        /// </summary>
        public static string IE {
            get {
                return ResourceManager.GetString("IE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iceland.
        /// </summary>
        public static string IS {
            get {
                return ResourceManager.GetString("IS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italy.
        /// </summary>
        public static string IT {
            get {
                return ResourceManager.GetString("IT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kazakhstan.
        /// </summary>
        public static string KZ {
            get {
                return ResourceManager.GetString("KZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liechtenstein.
        /// </summary>
        public static string LI {
            get {
                return ResourceManager.GetString("LI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lithuania.
        /// </summary>
        public static string LT {
            get {
                return ResourceManager.GetString("LT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luxembourg.
        /// </summary>
        public static string LU {
            get {
                return ResourceManager.GetString("LU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latvia.
        /// </summary>
        public static string LV {
            get {
                return ResourceManager.GetString("LV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monaco.
        /// </summary>
        public static string MC {
            get {
                return ResourceManager.GetString("MC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moldavia.
        /// </summary>
        public static string MD {
            get {
                return ResourceManager.GetString("MD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montenegro.
        /// </summary>
        public static string ME {
            get {
                return ResourceManager.GetString("ME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macedonia.
        /// </summary>
        public static string MK {
            get {
                return ResourceManager.GetString("MK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malta.
        /// </summary>
        public static string MT {
            get {
                return ResourceManager.GetString("MT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netherlands.
        /// </summary>
        public static string NL {
            get {
                return ResourceManager.GetString("NL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norway.
        /// </summary>
        public static string NO {
            get {
                return ResourceManager.GetString("NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poland.
        /// </summary>
        public static string PL {
            get {
                return ResourceManager.GetString("PL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portugal.
        /// </summary>
        public static string PT {
            get {
                return ResourceManager.GetString("PT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romania.
        /// </summary>
        public static string RO {
            get {
                return ResourceManager.GetString("RO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbia.
        /// </summary>
        public static string RS {
            get {
                return ResourceManager.GetString("RS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russia.
        /// </summary>
        public static string RU {
            get {
                return ResourceManager.GetString("RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweden.
        /// </summary>
        public static string SE {
            get {
                return ResourceManager.GetString("SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovenia.
        /// </summary>
        public static string SI {
            get {
                return ResourceManager.GetString("SI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovakia.
        /// </summary>
        public static string SK {
            get {
                return ResourceManager.GetString("SK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to San Marino.
        /// </summary>
        public static string SM {
            get {
                return ResourceManager.GetString("SM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tajikistan.
        /// </summary>
        public static string TJ {
            get {
                return ResourceManager.GetString("TJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkmenistan.
        /// </summary>
        public static string TM {
            get {
                return ResourceManager.GetString("TM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkey.
        /// </summary>
        public static string TR {
            get {
                return ResourceManager.GetString("TR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukraine.
        /// </summary>
        public static string UA {
            get {
                return ResourceManager.GetString("UA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzbekistan.
        /// </summary>
        public static string UZ {
            get {
                return ResourceManager.GetString("UZ", resourceCulture);
            }
        }
    }
}
