//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avelango.Resources.Pages.Fr {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class User {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal User() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Avelango.Resources.Pages.Fr.User", typeof(User).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to À propos de moi:.
        /// </summary>
        public static string ABOUTME {
            get {
                return ResourceManager.GetString("ABOUTME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to actes.
        /// </summary>
        public static string ACTIONS {
            get {
                return ResourceManager.GetString("ACTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter une image.
        /// </summary>
        public static string ADDIMAGE {
            get {
                return ResourceManager.GetString("ADDIMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string BALAN {
            get {
                return ResourceManager.GetString("BALAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de naissance.
        /// </summary>
        public static string BIRTHDAY {
            get {
                return ResourceManager.GetString("BIRTHDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soumettre portefeuille.
        /// </summary>
        public static string BTNADDJOBTOPORTFO {
            get {
                return ResourceManager.GetString("BTNADDJOBTOPORTFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string BTNCANCEL {
            get {
                return ResourceManager.GetString("BTNCANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changer de mot de passe.
        /// </summary>
        public static string BTNCHPASS {
            get {
                return ResourceManager.GetString("BTNCHPASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer ordre.
        /// </summary>
        public static string BTNCREATEORDER {
            get {
                return ResourceManager.GetString("BTNCREATEORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrer les modifications.
        /// </summary>
        public static string BTNSAVE {
            get {
                return ResourceManager.GetString("BTNSAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pays, ville.
        /// </summary>
        public static string COUNTCITY {
            get {
                return ResourceManager.GetString("COUNTCITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom du client.
        /// </summary>
        public static string CUSTOMERNAME {
            get {
                return ResourceManager.GetString("CUSTOMERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string DATE {
            get {
                return ResourceManager.GetString("DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EMAIL {
            get {
                return ResourceManager.GetString("EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Livraison E-mail.
        /// </summary>
        public static string EMAILDELIV {
            get {
                return ResourceManager.GetString("EMAILDELIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de Executor.
        /// </summary>
        public static string EXECUTORNAME {
            get {
                return ResourceManager.GetString("EXECUTORNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date d&apos;achèvement.
        /// </summary>
        public static string EXPIRDAY {
            get {
                return ResourceManager.GetString("EXPIRDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prénom.
        /// </summary>
        public static string FATHNAME {
            get {
                return ResourceManager.GetString("FATHNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Femelle.
        /// </summary>
        public static string FEMALE {
            get {
                return ResourceManager.GetString("FEMALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string FOTO {
            get {
                return ResourceManager.GetString("FOTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je suis un client.
        /// </summary>
        public static string ICUSTOM {
            get {
                return ResourceManager.GetString("ICUSTOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je suis un Executor.
        /// </summary>
        public static string IEXEC {
            get {
                return ResourceManager.GetString("IEXEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mâle.
        /// </summary>
        public static string MALE {
            get {
                return ResourceManager.GetString("MALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marque.
        /// </summary>
        public static string MARK {
            get {
                return ResourceManager.GetString("MARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examens.
        /// </summary>
        public static string MNEXAM {
            get {
                return ResourceManager.GetString("MNEXAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favoris.
        /// </summary>
        public static string MNFAVOR {
            get {
                return ResourceManager.GetString("MNFAVOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honneurs.
        /// </summary>
        public static string MNHONOR {
            get {
                return ResourceManager.GetString("MNHONOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string MNMESSAG {
            get {
                return ResourceManager.GetString("MNMESSAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon argent.
        /// </summary>
        public static string MNMONEY {
            get {
                return ResourceManager.GetString("MNMONEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes commandes.
        /// </summary>
        public static string MNMYORD {
            get {
                return ResourceManager.GetString("MNMYORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes œuvres.
        /// </summary>
        public static string MNMYWOR {
            get {
                return ResourceManager.GetString("MNMYWOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Données personnelles.
        /// </summary>
        public static string MNPERSDATA {
            get {
                return ResourceManager.GetString("MNPERSDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portefeuille.
        /// </summary>
        public static string MNPORTFO {
            get {
                return ResourceManager.GetString("MNPORTFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avis.
        /// </summary>
        public static string MNREVIEW {
            get {
                return ResourceManager.GetString("MNREVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groupes et abonnements.
        /// </summary>
        public static string MNSUBSCR {
            get {
                return ResourceManager.GetString("MNSUBSCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma page sur le site.
        /// </summary>
        public static string MYPAGE {
            get {
                return ResourceManager.GetString("MYPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        public static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De nouvelles informations sur le site.
        /// </summary>
        public static string NEWSITEINFO {
            get {
                return ResourceManager.GetString("NEWSITEINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ville.
        /// </summary>
        public static string PHCITY {
            get {
                return ResourceManager.GetString("PHCITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pays.
        /// </summary>
        public static string PHCOUNT {
            get {
                return ResourceManager.GetString("PHCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez votre adresse e-mail.
        /// </summary>
        public static string PHEMAIL {
            get {
                return ResourceManager.GetString("PHEMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez votre nom de famille.
        /// </summary>
        public static string PHFATHNAME {
            get {
                return ResourceManager.GetString("PHFATHNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header.
        /// </summary>
        public static string PHHEADER {
            get {
                return ResourceManager.GetString("PHHEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brève description (jusqu&apos;à 500 caractères).
        /// </summary>
        public static string PHJOBDESCRIPT {
            get {
                return ResourceManager.GetString("PHJOBDESCRIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titre du poste.
        /// </summary>
        public static string PHJOBTITLE {
            get {
                return ResourceManager.GetString("PHJOBTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez votre nom.
        /// </summary>
        public static string PHNAME {
            get {
                return ResourceManager.GetString("PHNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Téléphone.
        /// </summary>
        public static string PHONE {
            get {
                return ResourceManager.GetString("PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez votre numéro de téléphone 1.
        /// </summary>
        public static string PHPHONE1 {
            get {
                return ResourceManager.GetString("PHPHONE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez votre numéro de téléphone 2.
        /// </summary>
        public static string PHPHONE2 {
            get {
                return ResourceManager.GetString("PHPHONE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez votre numéro de téléphone 3.
        /// </summary>
        public static string PHPHONE3 {
            get {
                return ResourceManager.GetString("PHPHONE3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez Skype.
        /// </summary>
        public static string PHSKYPE {
            get {
                return ResourceManager.GetString("PHSKYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez le nom de famille.
        /// </summary>
        public static string PHSURNAME {
            get {
                return ResourceManager.GetString("PHSURNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications Push.
        /// </summary>
        public static string PUSHNOTIF {
            get {
                return ResourceManager.GetString("PUSHNOTIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation.
        /// </summary>
        public static string RATING {
            get {
                return ResourceManager.GetString("RATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En ligne.
        /// </summary>
        public static string REGFROM {
            get {
                return ResourceManager.GetString("REGFROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionner le groupe:.
        /// </summary>
        public static string SELECTGROUPS {
            get {
                return ResourceManager.GetString("SELECTGROUPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexe.
        /// </summary>
        public static string SEX {
            get {
                return ResourceManager.GetString("SEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype.
        /// </summary>
        public static string SKYPE {
            get {
                return ResourceManager.GetString("SKYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification par SMS.
        /// </summary>
        public static string SMSDELIV {
            get {
                return ResourceManager.GetString("SMSDELIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de lancement.
        /// </summary>
        public static string STARTDAY {
            get {
                return ResourceManager.GetString("STARTDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to statut.
        /// </summary>
        public static string STATUS {
            get {
                return ResourceManager.GetString("STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abonnez-vous à notre newsletter pour certains groupes:.
        /// </summary>
        public static string SUBSCRIBE {
            get {
                return ResourceManager.GetString("SUBSCRIBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somme.
        /// </summary>
        public static string SUMM {
            get {
                return ResourceManager.GetString("SUMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de famille.
        /// </summary>
        public static string SURNAME {
            get {
                return ResourceManager.GetString("SURNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emplois de texte.
        /// </summary>
        public static string TASKCONTENT {
            get {
                return ResourceManager.GetString("TASKCONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temps.
        /// </summary>
        public static string TIME {
            get {
                return ResourceManager.GetString("TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction.
        /// </summary>
        public static string TRANSACTION {
            get {
                return ResourceManager.GetString("TRANSACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenue dans l&apos;armoire.
        /// </summary>
        public static string WELLCOMETOACC {
            get {
                return ResourceManager.GetString("WELLCOMETOACC", resourceCulture);
            }
        }
    }
}
