//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avelango.Models.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatMessages
    {
        public int ID { get; set; }
        public System.Guid PublicKey { get; set; }
        public Nullable<int> BelongToChat { get; set; }
        public bool IsNew { get; set; }
        public System.DateTime Created { get; set; }
        public string Message { get; set; }
        public string AttachmentMin { get; set; }
        public string AttachmentMax { get; set; }
        public System.Guid Owner { get; set; }
    
        public virtual Chats Chats { get; set; }
    }
}
