//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avelango.Models.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notifications
    {
        public int ID { get; set; }
        public System.Guid PublicKey { get; set; }
        public Nullable<int> BelongsToTask { get; set; }
        public Nullable<int> BelongsToUser { get; set; }
        public Nullable<int> BelongsToFromUser { get; set; }
        public bool Reviewed { get; set; }
        public string NotificationType { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual Tasks Tasks { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
