//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avelango.Models.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class RialtoUsersStates
    {
        public int ID { get; set; }
        public double Ballance { get; set; }
        public int BelongsToUser { get; set; }
        public double Equity { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
