//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avelango.Models.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class RialtoState
    {
        public int ID { get; set; }
        public double TotalAveCount { get; set; }
        public double AveRate { get; set; }
        public double Benefit { get; set; }
        public int Shoulder { get; set; }
        public double BenefitPersent { get; set; }
    }
}
