//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avelango.Models.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class RialtoUserAssets
    {
        public int ID { get; set; }
        public double Value { get; set; }
        public double Rate { get; set; }
        public double Benefit { get; set; }
        public bool Sign { get; set; }
        public Nullable<int> BelongsToUser { get; set; }
        public Nullable<System.Guid> PublicKey { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
