//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avelango.Models.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class RialtoChat
    {
        public int ID { get; set; }
        public string SenderName { get; set; }
        public System.DateTime Created { get; set; }
        public string Message { get; set; }
    }
}
