//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avelango.Models.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmsSending
    {
        public int ID { get; set; }
        public Nullable<System.Guid> PublicKey { get; set; }
        public string Ip { get; set; }
        public int Counter { get; set; }
        public Nullable<System.DateTime> ResetTime { get; set; }
        public string Phone { get; set; }
    }
}
