//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avelango.Models.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskAttachments
    {
        public int ID { get; set; }
        public System.Guid PublicKey { get; set; }
        public Nullable<int> BelongsToTask { get; set; }
        public string Url { get; set; }
        public string Extention { get; set; }
        public string FileTitle { get; set; }
    
        public virtual Tasks Tasks { get; set; }
    }
}
