//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avelango.Models.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskBids
    {
        public int ID { get; set; }
        public System.Guid PublicKey { get; set; }
        public Nullable<int> BelongsToTask { get; set; }
        public string Message { get; set; }
        public int Price { get; set; }
        public System.DateTime Created { get; set; }
        public bool Denied { get; set; }
        public Nullable<int> BelongsToWorker { get; set; }
    
        public virtual Tasks Tasks { get; set; }
        public virtual Users Users { get; set; }
    }
}
