//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avelango.Models.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tasks()
        {
            this.Notifications = new HashSet<Notifications>();
            this.TaskAttachments = new HashSet<TaskAttachments>();
            this.TaskBids = new HashSet<TaskBids>();
            this.TaskOffers = new HashSet<TaskOffers>();
            this.TaskPreWorkers = new HashSet<TaskPreWorkers>();
        }
    
        public int ID { get; set; }
        public System.Guid PublicKey { get; set; }
        public int Customer { get; set; }
        public Nullable<int> Worker { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime TopicalTo { get; set; }
        public System.DateTime Created { get; set; }
        public string Groop { get; set; }
        public string SubGroop { get; set; }
        public int Price { get; set; }
        public string ProccessStatus { get; set; }
        public Nullable<bool> IsRemovedToCustomer { get; set; }
        public Nullable<System.DateTime> Closed { get; set; }
        public Nullable<bool> IsRemovedToWorker { get; set; }
        public string PlaceName { get; set; }
        public Nullable<double> PlaceLat { get; set; }
        public Nullable<double> PlaceLng { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notifications> Notifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskAttachments> TaskAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskBids> TaskBids { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskOffers> TaskOffers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskPreWorkers> TaskPreWorkers { get; set; }
    }
}
