//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avelango.Resources.Email {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Avelango.Resources.Email.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.avelango.com/Users/Executors.
        /// </summary>
        public static string HrefAllExecutors {
            get {
                return ResourceManager.GetString("HrefAllExecutors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.avelango.com/Task/Tasks.
        /// </summary>
        public static string HrefAllTasks {
            get {
                return ResourceManager.GetString("HrefAllTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.avelango.com/account/confirm?tempid=.
        /// </summary>
        public static string HrefConfirm {
            get {
                return ResourceManager.GetString("HrefConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.avelango.com.
        /// </summary>
        public static string HrefNewsOnSite {
            get {
                return ResourceManager.GetString("HrefNewsOnSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.avelango.com.
        /// </summary>
        public static string HrefNewsUnsubscribe {
            get {
                return ResourceManager.GetString("HrefNewsUnsubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.avelango.com.
        /// </summary>
        public static string HrefRecovery {
            get {
                return ResourceManager.GetString("HrefRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.avelango.com.
        /// </summary>
        public static string HrefRemove {
            get {
                return ResourceManager.GetString("HrefRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.avelango.com.
        /// </summary>
        public static string HrefSiteUri {
            get {
                return ResourceManager.GetString("HrefSiteUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.avelango.com.
        /// </summary>
        public static string HrefToParlour {
            get {
                return ResourceManager.GetString("HrefToParlour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.avelango.com/Home/Rules.
        /// </summary>
        public static string HrefToRules {
            get {
                return ResourceManager.GetString("HrefToRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.avelango.com.
        /// </summary>
        public static string HrefToTask {
            get {
                return ResourceManager.GetString("HrefToTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info@avelango.com.
        /// </summary>
        public static string InfoMail {
            get {
                return ResourceManager.GetString("InfoMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://vk.com/club127950535.
        /// </summary>
        public static string LnkLoginFacebook {
            get {
                return ResourceManager.GetString("LnkLoginFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://vk.com/club127950535.
        /// </summary>
        public static string LnkLoginGoogle {
            get {
                return ResourceManager.GetString("LnkLoginGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://vk.com/club127950535.
        /// </summary>
        public static string LnkLoginInstagram {
            get {
                return ResourceManager.GetString("LnkLoginInstagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://vk.com/club127950535.
        /// </summary>
        public static string LnkLoginLinkedin {
            get {
                return ResourceManager.GetString("LnkLoginLinkedin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://vk.com/club127950535.
        /// </summary>
        public static string LnkLoginTwitter {
            get {
                return ResourceManager.GetString("LnkLoginTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://vk.com/club127950535.
        /// </summary>
        public static string LnkLoginVK {
            get {
                return ResourceManager.GetString("LnkLoginVK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to support@avelango.com.
        /// </summary>
        public static string SupportMail {
            get {
                return ResourceManager.GetString("SupportMail", resourceCulture);
            }
        }
    }
}
