//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avelango.Resources.Groups.En {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Groups {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Groups() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Avelango.Resources.Groups.En.Groups", typeof(Groups).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Курьеры.
        /// </summary>
        public static string A {
            get {
                return ResourceManager.GetString("A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автокурьер.
        /// </summary>
        public static string A1 {
            get {
                return ResourceManager.GetString("A1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Круглосуточно.
        /// </summary>
        public static string A2 {
            get {
                return ResourceManager.GetString("A2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Междугородные.
        /// </summary>
        public static string A3 {
            get {
                return ResourceManager.GetString("A3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Международные.
        /// </summary>
        public static string A4 {
            get {
                return ResourceManager.GetString("A4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пешие и вело.
        /// </summary>
        public static string A5 {
            get {
                return ResourceManager.GetString("A5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Другие.
        /// </summary>
        public static string A6 {
            get {
                return ResourceManager.GetString("A6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поручения.
        /// </summary>
        public static string B {
            get {
                return ResourceManager.GetString("B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Купить и доставить.
        /// </summary>
        public static string B1 {
            get {
                return ResourceManager.GetString("B1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Междугородные.
        /// </summary>
        public static string B2 {
            get {
                return ResourceManager.GetString("B2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Международные.
        /// </summary>
        public static string B3 {
            get {
                return ResourceManager.GetString("B3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поздравления и подарки.
        /// </summary>
        public static string B4 {
            get {
                return ResourceManager.GetString("B4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Срочные.
        /// </summary>
        public static string B5 {
            get {
                return ResourceManager.GetString("B5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Другие.
        /// </summary>
        public static string B6 {
            get {
                return ResourceManager.GetString("B6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Быт.
        /// </summary>
        public static string C {
            get {
                return ResourceManager.GetString("C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бытовой ремонт.
        /// </summary>
        public static string C1 {
            get {
                return ResourceManager.GetString("C1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Погладить, постирать.
        /// </summary>
        public static string C10 {
            get {
                return ResourceManager.GetString("C10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пошив и ремонт изделий.
        /// </summary>
        public static string C11 {
            get {
                return ResourceManager.GetString("C11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приготовление еды.
        /// </summary>
        public static string C12 {
            get {
                return ResourceManager.GetString("C12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ремонт техники.
        /// </summary>
        public static string C13 {
            get {
                return ResourceManager.GetString("C13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сад, огород.
        /// </summary>
        public static string C2 {
            get {
                return ResourceManager.GetString("C2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сторойка, ремонт.
        /// </summary>
        public static string C3 {
            get {
                return ResourceManager.GetString("C3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уборка.
        /// </summary>
        public static string C4 {
            get {
                return ResourceManager.GetString("C4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Другое.
        /// </summary>
        public static string C5 {
            get {
                return ResourceManager.GetString("C5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Домработницы.
        /// </summary>
        public static string C6 {
            get {
                return ResourceManager.GetString("C6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изготовление и ремонт мебели.
        /// </summary>
        public static string C7 {
            get {
                return ResourceManager.GetString("C7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мелкий ремонт.
        /// </summary>
        public static string C8 {
            get {
                return ResourceManager.GetString("C8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Няни, сиделки.
        /// </summary>
        public static string C9 {
            get {
                return ResourceManager.GetString("C9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перевозки.
        /// </summary>
        public static string D {
            get {
                return ResourceManager.GetString("D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вывоз мусора.
        /// </summary>
        public static string D1 {
            get {
                return ResourceManager.GetString("D1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грузоперевозки.
        /// </summary>
        public static string D2 {
            get {
                return ResourceManager.GetString("D2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грузчики.
        /// </summary>
        public static string D3 {
            get {
                return ResourceManager.GetString("D3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Международные перевозки.
        /// </summary>
        public static string D4 {
            get {
                return ResourceManager.GetString("D4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пассажирские перевозки.
        /// </summary>
        public static string D5 {
            get {
                return ResourceManager.GetString("D5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переезды.
        /// </summary>
        public static string D6 {
            get {
                return ResourceManager.GetString("D6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эвакуатор, буксировка.
        /// </summary>
        public static string D7 {
            get {
                return ResourceManager.GetString("D7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Другие.
        /// </summary>
        public static string D8 {
            get {
                return ResourceManager.GetString("D8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Клининг.
        /// </summary>
        public static string E {
            get {
                return ResourceManager.GetString("E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Генеральная уборка.
        /// </summary>
        public static string E1 {
            get {
                return ResourceManager.GetString("E1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Легкая уборка.
        /// </summary>
        public static string E2 {
            get {
                return ResourceManager.GetString("E2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мойка машин.
        /// </summary>
        public static string E3 {
            get {
                return ResourceManager.GetString("E3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мытье окон.
        /// </summary>
        public static string E4 {
            get {
                return ResourceManager.GetString("E4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регулярная уборка.
        /// </summary>
        public static string E5 {
            get {
                return ResourceManager.GetString("E5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Специальная уборка.
        /// </summary>
        public static string E6 {
            get {
                return ResourceManager.GetString("E6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уборка территорий, ландшафт.
        /// </summary>
        public static string E7 {
            get {
                return ResourceManager.GetString("E7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чистка оборудования.
        /// </summary>
        public static string E8 {
            get {
                return ResourceManager.GetString("E8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Другое.
        /// </summary>
        public static string E9 {
            get {
                return ResourceManager.GetString("E9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT.
        /// </summary>
        public static string F {
            get {
                return ResourceManager.GetString("F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дизайн.
        /// </summary>
        public static string F1 {
            get {
                return ResourceManager.GetString("F1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сайты.
        /// </summary>
        public static string F10 {
            get {
                return ResourceManager.GetString("F10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Другое.
        /// </summary>
        public static string F2 {
            get {
                return ResourceManager.GetString("F2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игры.
        /// </summary>
        public static string F3 {
            get {
                return ResourceManager.GetString("F3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копирайт и рерайт.
        /// </summary>
        public static string F4 {
            get {
                return ResourceManager.GetString("F4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переводы.
        /// </summary>
        public static string F5 {
            get {
                return ResourceManager.GetString("F5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск информации.
        /// </summary>
        public static string F6 {
            get {
                return ResourceManager.GetString("F6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приложения.
        /// </summary>
        public static string F7 {
            get {
                return ResourceManager.GetString("F7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продвижение.
        /// </summary>
        public static string F8 {
            get {
                return ResourceManager.GetString("F8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Программы.
        /// </summary>
        public static string F9 {
            get {
                return ResourceManager.GetString("F9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бизнес.
        /// </summary>
        public static string G {
            get {
                return ResourceManager.GetString("G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адвокаты.
        /// </summary>
        public static string G1 {
            get {
                return ResourceManager.GetString("G1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переводы.
        /// </summary>
        public static string G10 {
            get {
                return ResourceManager.GetString("G10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация и ликвидация компаний.
        /// </summary>
        public static string G11 {
            get {
                return ResourceManager.GetString("G11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реклама и продвижение.
        /// </summary>
        public static string G12 {
            get {
                return ResourceManager.GetString("G12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таможня.
        /// </summary>
        public static string G2 {
            get {
                return ResourceManager.GetString("G2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Юридическая поддержка.
        /// </summary>
        public static string G3 {
            get {
                return ResourceManager.GetString("G3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Другое.
        /// </summary>
        public static string G4 {
            get {
                return ResourceManager.GetString("G4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Безопасность.
        /// </summary>
        public static string G5 {
            get {
                return ResourceManager.GetString("G5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бугхалтерия и финансы.
        /// </summary>
        public static string G6 {
            get {
                return ResourceManager.GetString("G6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видео и фото улуги.
        /// </summary>
        public static string G7 {
            get {
                return ResourceManager.GetString("G7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кадры и рекрутинг.
        /// </summary>
        public static string G8 {
            get {
                return ResourceManager.GetString("G8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Консалтинг.
        /// </summary>
        public static string G9 {
            get {
                return ResourceManager.GetString("G9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Образование.
        /// </summary>
        public static string H {
            get {
                return ResourceManager.GetString("H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для маленьких детей.
        /// </summary>
        public static string H1 {
            get {
                return ResourceManager.GetString("H1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задать вопрос.
        /// </summary>
        public static string H2 {
            get {
                return ResourceManager.GetString("H2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Курсы, тренинги и семинары.
        /// </summary>
        public static string H3 {
            get {
                return ResourceManager.GetString("H3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логопед.
        /// </summary>
        public static string H4 {
            get {
                return ResourceManager.GetString("H4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переводы.
        /// </summary>
        public static string H5 {
            get {
                return ResourceManager.GetString("H5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Репетиторы и преподаватели.
        /// </summary>
        public static string H6 {
            get {
                return ResourceManager.GetString("H6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рефераты, курсовые и пр..
        /// </summary>
        public static string H7 {
            get {
                return ResourceManager.GetString("H7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Другое.
        /// </summary>
        public static string H8 {
            get {
                return ResourceManager.GetString("H8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здоровье.
        /// </summary>
        public static string I {
            get {
                return ResourceManager.GetString("I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Психолоия и психиатрия.
        /// </summary>
        public static string I10 {
            get {
                return ResourceManager.GetString("I10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Семейный врач.
        /// </summary>
        public static string I11 {
            get {
                return ResourceManager.GetString("I11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Врачи и вызов на дом.
        /// </summary>
        public static string I2 {
            get {
                return ResourceManager.GetString("I2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Другое.
        /// </summary>
        public static string I3 {
            get {
                return ResourceManager.GetString("I3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детский доктор.
        /// </summary>
        public static string I4 {
            get {
                return ResourceManager.GetString("I4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Диетологи.
        /// </summary>
        public static string I5 {
            get {
                return ResourceManager.GetString("I5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лечебный массаж.
        /// </summary>
        public static string I6 {
            get {
                return ResourceManager.GetString("I6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лечение зависимостей.
        /// </summary>
        public static string I7 {
            get {
                return ResourceManager.GetString("I7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лечение зарубежом.
        /// </summary>
        public static string I8 {
            get {
                return ResourceManager.GetString("I8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Народная медицина.
        /// </summary>
        public static string I9 {
            get {
                return ResourceManager.GetString("I9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Красота.
        /// </summary>
        public static string J {
            get {
                return ResourceManager.GetString("J", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Визаж и макияж.
        /// </summary>
        public static string J1 {
            get {
                return ResourceManager.GetString("J1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пластика, импланты.
        /// </summary>
        public static string J10 {
            get {
                return ResourceManager.GetString("J10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стиль и имидж.
        /// </summary>
        public static string J11 {
            get {
                return ResourceManager.GetString("J11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тату и бодиарт.
        /// </summary>
        public static string J2 {
            get {
                return ResourceManager.GetString("J2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Другое.
        /// </summary>
        public static string J3 {
            get {
                return ResourceManager.GetString("J3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Волосы.
        /// </summary>
        public static string J4 {
            get {
                return ResourceManager.GetString("J4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дерматология.
        /// </summary>
        public static string J5 {
            get {
                return ResourceManager.GetString("J5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задать вопрос.
        /// </summary>
        public static string J6 {
            get {
                return ResourceManager.GetString("J6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Косметология.
        /// </summary>
        public static string J7 {
            get {
                return ResourceManager.GetString("J7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Массаж.
        /// </summary>
        public static string J8 {
            get {
                return ResourceManager.GetString("J8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ногти.
        /// </summary>
        public static string J9 {
            get {
                return ResourceManager.GetString("J9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мероприятия.
        /// </summary>
        public static string K {
            get {
                return ResourceManager.GetString("K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выставки, семинары, презентации.
        /// </summary>
        public static string K1 {
            get {
                return ResourceManager.GetString("K1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BTL.
        /// </summary>
        public static string K10 {
            get {
                return ResourceManager.GetString("K10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Другое.
        /// </summary>
        public static string K2 {
            get {
                return ResourceManager.GetString("K2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дни рождения, корпоративы.
        /// </summary>
        public static string K3 {
            get {
                return ResourceManager.GetString("K3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кейтеринг.
        /// </summary>
        public static string K4 {
            get {
                return ResourceManager.GetString("K4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Организация встреч, сопровождение.
        /// </summary>
        public static string K5 {
            get {
                return ResourceManager.GetString("K5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оформление и декорирование.
        /// </summary>
        public static string K6 {
            get {
                return ResourceManager.GetString("K6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спорт.
        /// </summary>
        public static string K7 {
            get {
                return ResourceManager.GetString("K7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Флешмоб.
        /// </summary>
        public static string K8 {
            get {
                return ResourceManager.GetString("K8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экскурсии.
        /// </summary>
        public static string K9 {
            get {
                return ResourceManager.GetString("K9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Животные.
        /// </summary>
        public static string L {
            get {
                return ResourceManager.GetString("L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аквариум, террариум.
        /// </summary>
        public static string L1 {
            get {
                return ResourceManager.GetString("L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гостиницы для животных.
        /// </summary>
        public static string L2 {
            get {
                return ResourceManager.GetString("L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дресировка.
        /// </summary>
        public static string L3 {
            get {
                return ResourceManager.GetString("L3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Клиники и ветеринары.
        /// </summary>
        public static string L4 {
            get {
                return ResourceManager.GetString("L4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Красота.
        /// </summary>
        public static string L5 {
            get {
                return ResourceManager.GetString("L5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Случка.
        /// </summary>
        public static string L6 {
            get {
                return ResourceManager.GetString("L6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уход за животными, выгул.
        /// </summary>
        public static string L7 {
            get {
                return ResourceManager.GetString("L7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Другое.
        /// </summary>
        public static string L8 {
            get {
                return ResourceManager.GetString("L8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Другое.
        /// </summary>
        public static string M {
            get {
                return ResourceManager.GetString("M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вопрос на любую тему.
        /// </summary>
        public static string M1 {
            get {
                return ResourceManager.GetString("M1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Знакомства.
        /// </summary>
        public static string M2 {
            get {
                return ResourceManager.GetString("M2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Массаж.
        /// </summary>
        public static string M3 {
            get {
                return ResourceManager.GetString("M3", resourceCulture);
            }
        }
    }
}
