//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avelango.Resources.Modals.Fr {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CreateOrder {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreateOrder() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Avelango.Resources.Modals.Fr.CreateOrder", typeof(CreateOrder).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important.
        /// </summary>
        public static string ACTUALTIME {
            get {
                return ResourceManager.GetString("ACTUALTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string BTNCANCEL {
            get {
                return ResourceManager.GetString("BTNCANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouvel emploi.
        /// </summary>
        public static string CREATEORDER {
            get {
                return ResourceManager.GetString("CREATEORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to РОМПРМРО.
        /// </summary>
        public static string EDITORDER {
            get {
                return ResourceManager.GetString("EDITORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ville.
        /// </summary>
        public static string ORDERCITY {
            get {
                return ResourceManager.GetString("ORDERCITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pays.
        /// </summary>
        public static string ORDERCOUNTRY {
            get {
                return ResourceManager.GetString("ORDERCOUNTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ORDERDESCRIPT {
            get {
                return ResourceManager.GetString("ORDERDESCRIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tête.
        /// </summary>
        public static string ORDERNAME {
            get {
                return ResourceManager.GetString("ORDERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somme.
        /// </summary>
        public static string ORDERPRICE {
            get {
                return ResourceManager.GetString("ORDERPRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce champ est obligatoire.
        /// </summary>
        public static string REQUIREDFIELD {
            get {
                return ResourceManager.GetString("REQUIREDFIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temps.
        /// </summary>
        public static string TIME {
            get {
                return ResourceManager.GetString("TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce champ ne est pas rempli droit.
        /// </summary>
        public static string VALIDFIELD {
            get {
                return ResourceManager.GetString("VALIDFIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doit être un nombre valide.
        /// </summary>
        public static string VALIDNUMBER {
            get {
                return ResourceManager.GetString("VALIDNUMBER", resourceCulture);
            }
        }
    }
}
