//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avelango.Resources.Pages.De {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class User {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal User() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Avelango.Resources.Pages.De.User", typeof(User).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Über mich:.
        /// </summary>
        public static string ABOUTME {
            get {
                return ResourceManager.GetString("ABOUTME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktionen.
        /// </summary>
        public static string ACTIONS {
            get {
                return ResourceManager.GetString("ACTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild hinzufügen.
        /// </summary>
        public static string ADDIMAGE {
            get {
                return ResourceManager.GetString("ADDIMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string BALAN {
            get {
                return ResourceManager.GetString("BALAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geburtsdatum.
        /// </summary>
        public static string BIRTHDAY {
            get {
                return ResourceManager.GetString("BIRTHDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senden Portfolio.
        /// </summary>
        public static string BTNADDJOBTOPORTFO {
            get {
                return ResourceManager.GetString("BTNADDJOBTOPORTFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stornieren.
        /// </summary>
        public static string BTNCANCEL {
            get {
                return ResourceManager.GetString("BTNCANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort ändern.
        /// </summary>
        public static string BTNCHPASS {
            get {
                return ResourceManager.GetString("BTNCHPASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstellen Sie bestellen.
        /// </summary>
        public static string BTNCREATEORDER {
            get {
                return ResourceManager.GetString("BTNCREATEORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Änderungen speichern.
        /// </summary>
        public static string BTNSAVE {
            get {
                return ResourceManager.GetString("BTNSAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land, Stadt.
        /// </summary>
        public static string COUNTCITY {
            get {
                return ResourceManager.GetString("COUNTCITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kundenname .
        /// </summary>
        public static string CUSTOMERNAME {
            get {
                return ResourceManager.GetString("CUSTOMERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        public static string DATE {
            get {
                return ResourceManager.GetString("DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string EMAIL {
            get {
                return ResourceManager.GetString("EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail-Übermittlung.
        /// </summary>
        public static string EMAILDELIV {
            get {
                return ResourceManager.GetString("EMAILDELIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executor Name.
        /// </summary>
        public static string EXECUTORNAME {
            get {
                return ResourceManager.GetString("EXECUTORNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum der Fertigstellung.
        /// </summary>
        public static string EXPIRDAY {
            get {
                return ResourceManager.GetString("EXPIRDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zweiter Vorname.
        /// </summary>
        public static string FATHNAME {
            get {
                return ResourceManager.GetString("FATHNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weiblich.
        /// </summary>
        public static string FEMALE {
            get {
                return ResourceManager.GetString("FEMALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto.
        /// </summary>
        public static string FOTO {
            get {
                return ResourceManager.GetString("FOTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ich bin ein Kunde.
        /// </summary>
        public static string ICUSTOM {
            get {
                return ResourceManager.GetString("ICUSTOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ich bin ein Executor.
        /// </summary>
        public static string IEXEC {
            get {
                return ResourceManager.GetString("IEXEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Männlich.
        /// </summary>
        public static string MALE {
            get {
                return ResourceManager.GetString("MALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark.
        /// </summary>
        public static string MARK {
            get {
                return ResourceManager.GetString("MARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prüfungen.
        /// </summary>
        public static string MNEXAM {
            get {
                return ResourceManager.GetString("MNEXAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favoriten.
        /// </summary>
        public static string MNFAVOR {
            get {
                return ResourceManager.GetString("MNFAVOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ehrungen.
        /// </summary>
        public static string MNHONOR {
            get {
                return ResourceManager.GetString("MNHONOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nachrichten.
        /// </summary>
        public static string MNMESSAG {
            get {
                return ResourceManager.GetString("MNMESSAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mein Geld.
        /// </summary>
        public static string MNMONEY {
            get {
                return ResourceManager.GetString("MNMONEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meine Bestellungen.
        /// </summary>
        public static string MNMYORD {
            get {
                return ResourceManager.GetString("MNMYORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meine Arbeiten.
        /// </summary>
        public static string MNMYWOR {
            get {
                return ResourceManager.GetString("MNMYWOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persönliche Daten.
        /// </summary>
        public static string MNPERSDATA {
            get {
                return ResourceManager.GetString("MNPERSDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mappe.
        /// </summary>
        public static string MNPORTFO {
            get {
                return ResourceManager.GetString("MNPORTFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bewertungen.
        /// </summary>
        public static string MNREVIEW {
            get {
                return ResourceManager.GetString("MNREVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gruppen und Abonnements.
        /// </summary>
        public static string MNSUBSCR {
            get {
                return ResourceManager.GetString("MNSUBSCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meine Seite auf der Seite.
        /// </summary>
        public static string MYPAGE {
            get {
                return ResourceManager.GetString("MYPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Informationen vor Ort.
        /// </summary>
        public static string NEWSITEINFO {
            get {
                return ResourceManager.GetString("NEWSITEINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string PHCITY {
            get {
                return ResourceManager.GetString("PHCITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land.
        /// </summary>
        public static string PHCOUNT {
            get {
                return ResourceManager.GetString("PHCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geben Sie einfach Ihre E-Mail-Adresse.
        /// </summary>
        public static string PHEMAIL {
            get {
                return ResourceManager.GetString("PHEMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geben Sie Ihren Nachnamen.
        /// </summary>
        public static string PHFATHNAME {
            get {
                return ResourceManager.GetString("PHFATHNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopfzeile .
        /// </summary>
        public static string PHHEADER {
            get {
                return ResourceManager.GetString("PHHEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurzbeschreibung (bis zu 500 Zeichen).
        /// </summary>
        public static string PHJOBDESCRIPT {
            get {
                return ResourceManager.GetString("PHJOBDESCRIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stellenbezeichnung .
        /// </summary>
        public static string PHJOBTITLE {
            get {
                return ResourceManager.GetString("PHJOBTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geben Sie Ihren Namen.
        /// </summary>
        public static string PHNAME {
            get {
                return ResourceManager.GetString("PHNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string PHONE {
            get {
                return ResourceManager.GetString("PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geben Sie Ihre Telefonnummer 1.
        /// </summary>
        public static string PHPHONE1 {
            get {
                return ResourceManager.GetString("PHPHONE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geben Sie Ihre Telefonnummer 2.
        /// </summary>
        public static string PHPHONE2 {
            get {
                return ResourceManager.GetString("PHPHONE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geben Sie Ihre Telefonnummer 3.
        /// </summary>
        public static string PHPHONE3 {
            get {
                return ResourceManager.GetString("PHPHONE3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geben Sie Skype.
        /// </summary>
        public static string PHSKYPE {
            get {
                return ResourceManager.GetString("PHSKYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geben Sie den Namen.
        /// </summary>
        public static string PHSURNAME {
            get {
                return ResourceManager.GetString("PHSURNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push-Benachrichtigungen.
        /// </summary>
        public static string PUSHNOTIF {
            get {
                return ResourceManager.GetString("PUSHNOTIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wertung.
        /// </summary>
        public static string RATING {
            get {
                return ResourceManager.GetString("RATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string REGFROM {
            get {
                return ResourceManager.GetString("REGFROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gruppe auswählen:.
        /// </summary>
        public static string SELECTGROUPS {
            get {
                return ResourceManager.GetString("SELECTGROUPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        public static string SEX {
            get {
                return ResourceManager.GetString("SEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype.
        /// </summary>
        public static string SKYPE {
            get {
                return ResourceManager.GetString("SKYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS Benachrichtigung.
        /// </summary>
        public static string SMSDELIV {
            get {
                return ResourceManager.GetString("SMSDELIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auflegungsdatum .
        /// </summary>
        public static string STARTDAY {
            get {
                return ResourceManager.GetString("STARTDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string STATUS {
            get {
                return ResourceManager.GetString("STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abonnieren Sie unseren Newsletter zu ausgewählten Gruppen:.
        /// </summary>
        public static string SUBSCRIBE {
            get {
                return ResourceManager.GetString("SUBSCRIBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summe.
        /// </summary>
        public static string SUMM {
            get {
                return ResourceManager.GetString("SUMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nachname.
        /// </summary>
        public static string SURNAME {
            get {
                return ResourceManager.GetString("SURNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Jobs.
        /// </summary>
        public static string TASKCONTENT {
            get {
                return ResourceManager.GetString("TASKCONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeit.
        /// </summary>
        public static string TIME {
            get {
                return ResourceManager.GetString("TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaktion.
        /// </summary>
        public static string TRANSACTION {
            get {
                return ResourceManager.GetString("TRANSACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Willkommen im Schrank.
        /// </summary>
        public static string WELLCOMETOACC {
            get {
                return ResourceManager.GetString("WELLCOMETOACC", resourceCulture);
            }
        }
    }
}
