//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avelango.Resources.Locations.Fr {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Countries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Countries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Avelango.Resources.Locations.Fr.Countries", typeof(Countries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andorre.
        /// </summary>
        public static string AD {
            get {
                return ResourceManager.GetString("AD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albanie.
        /// </summary>
        public static string AL {
            get {
                return ResourceManager.GetString("AL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arménie.
        /// </summary>
        public static string AM {
            get {
                return ResourceManager.GetString("AM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autriche.
        /// </summary>
        public static string AT {
            get {
                return ResourceManager.GetString("AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azerbaïdjan.
        /// </summary>
        public static string AZ {
            get {
                return ResourceManager.GetString("AZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosnie-Herzégovine.
        /// </summary>
        public static string BA {
            get {
                return ResourceManager.GetString("BA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belgique.
        /// </summary>
        public static string BE {
            get {
                return ResourceManager.GetString("BE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulgarie.
        /// </summary>
        public static string BG {
            get {
                return ResourceManager.GetString("BG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belarus.
        /// </summary>
        public static string BY {
            get {
                return ResourceManager.GetString("BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suisse.
        /// </summary>
        public static string CH {
            get {
                return ResourceManager.GetString("CH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to République tchèque.
        /// </summary>
        public static string CZ {
            get {
                return ResourceManager.GetString("CZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allemagne.
        /// </summary>
        public static string DE {
            get {
                return ResourceManager.GetString("DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danemark.
        /// </summary>
        public static string DK {
            get {
                return ResourceManager.GetString("DK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estonie.
        /// </summary>
        public static string EE {
            get {
                return ResourceManager.GetString("EE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espagne.
        /// </summary>
        public static string ES {
            get {
                return ResourceManager.GetString("ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finlande.
        /// </summary>
        public static string FI {
            get {
                return ResourceManager.GetString("FI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to France.
        /// </summary>
        public static string FR {
            get {
                return ResourceManager.GetString("FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Royaume-Uni.
        /// </summary>
        public static string GB {
            get {
                return ResourceManager.GetString("GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Géorgie.
        /// </summary>
        public static string GE {
            get {
                return ResourceManager.GetString("GE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grèce.
        /// </summary>
        public static string GR {
            get {
                return ResourceManager.GetString("GR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatie.
        /// </summary>
        public static string HR {
            get {
                return ResourceManager.GetString("HR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hongrie.
        /// </summary>
        public static string HU {
            get {
                return ResourceManager.GetString("HU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irlande.
        /// </summary>
        public static string IE {
            get {
                return ResourceManager.GetString("IE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Islande.
        /// </summary>
        public static string IS {
            get {
                return ResourceManager.GetString("IS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italie.
        /// </summary>
        public static string IT {
            get {
                return ResourceManager.GetString("IT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kazakhstan.
        /// </summary>
        public static string KZ {
            get {
                return ResourceManager.GetString("KZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liechtenstein.
        /// </summary>
        public static string LI {
            get {
                return ResourceManager.GetString("LI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lituanie.
        /// </summary>
        public static string LT {
            get {
                return ResourceManager.GetString("LT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luxembourg.
        /// </summary>
        public static string LU {
            get {
                return ResourceManager.GetString("LU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lettonie.
        /// </summary>
        public static string LV {
            get {
                return ResourceManager.GetString("LV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monaco.
        /// </summary>
        public static string MC {
            get {
                return ResourceManager.GetString("MC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moldavie.
        /// </summary>
        public static string MD {
            get {
                return ResourceManager.GetString("MD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monténégro.
        /// </summary>
        public static string ME {
            get {
                return ResourceManager.GetString("ME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macédoine.
        /// </summary>
        public static string MK {
            get {
                return ResourceManager.GetString("MK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malte.
        /// </summary>
        public static string MT {
            get {
                return ResourceManager.GetString("MT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pays-Bas.
        /// </summary>
        public static string NL {
            get {
                return ResourceManager.GetString("NL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norvège.
        /// </summary>
        public static string NO {
            get {
                return ResourceManager.GetString("NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pologne.
        /// </summary>
        public static string PL {
            get {
                return ResourceManager.GetString("PL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portugal.
        /// </summary>
        public static string PT {
            get {
                return ResourceManager.GetString("PT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roumanie.
        /// </summary>
        public static string RO {
            get {
                return ResourceManager.GetString("RO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbie.
        /// </summary>
        public static string RS {
            get {
                return ResourceManager.GetString("RS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russie.
        /// </summary>
        public static string RU {
            get {
                return ResourceManager.GetString("RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suède.
        /// </summary>
        public static string SE {
            get {
                return ResourceManager.GetString("SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovénie.
        /// </summary>
        public static string SI {
            get {
                return ResourceManager.GetString("SI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovaquie.
        /// </summary>
        public static string SK {
            get {
                return ResourceManager.GetString("SK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to San Marino.
        /// </summary>
        public static string SM {
            get {
                return ResourceManager.GetString("SM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tadjikistan.
        /// </summary>
        public static string TJ {
            get {
                return ResourceManager.GetString("TJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkménistan.
        /// </summary>
        public static string TM {
            get {
                return ResourceManager.GetString("TM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turquie.
        /// </summary>
        public static string TR {
            get {
                return ResourceManager.GetString("TR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukraine.
        /// </summary>
        public static string UA {
            get {
                return ResourceManager.GetString("UA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouzbékistan.
        /// </summary>
        public static string UZ {
            get {
                return ResourceManager.GetString("UZ", resourceCulture);
            }
        }
    }
}
