//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avelango.Resources.Email.Ua {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Content {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Content() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Avelango.Resources.Email.Ua.Content", typeof(Content).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Огляд виконавців.
        /// </summary>
        public static string BtnAllExecutors {
            get {
                return ResourceManager.GetString("BtnAllExecutors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Огляд завдань.
        /// </summary>
        public static string BtnAllTasks {
            get {
                return ResourceManager.GetString("BtnAllTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дізнатися більше.
        /// </summary>
        public static string BtnLearnMore {
            get {
                return ResourceManager.GetString("BtnLearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш аккаунт на сайті деактивовано.
        /// </summary>
        public static string DeactHeader {
            get {
                return ResourceManager.GetString("DeactHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Deactivation {
            get {
                return ResourceManager.GetString("Deactivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Деактивація на Avelango.com.
        /// </summary>
        public static string DeactMail {
            get {
                return ResourceManager.GetString("DeactMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ознайомитися з правилами сайту.
        /// </summary>
        public static string DeactMessage {
            get {
                return ResourceManager.GetString("DeactMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Деактивація - блокування можливості використовувати свій аккаунт. При цьому Ваші дані будуть збережені..
        /// </summary>
        public static string DeactNote {
            get {
                return ResourceManager.GetString("DeactNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш аккаунт на сайті видалений.
        /// </summary>
        public static string DeleteHeader {
            get {
                return ResourceManager.GetString("DeleteHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалення аккаунта на Avelango.com.
        /// </summary>
        public static string DeleteMail {
            get {
                return ResourceManager.GetString("DeleteMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Правила сайту.
        /// </summary>
        public static string DeleteMessage {
            get {
                return ResourceManager.GetString("DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Видалення аккаунта - видалення даних вашого облікового запису без можливості їх відновлення..
        /// </summary>
        public static string DeleteNote {
            get {
                return ResourceManager.GetString("DeleteNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цей лист відправлено автоматично, на нього не потрібно відповідати..
        /// </summary>
        public static string DontResponse {
            get {
                return ResourceManager.GetString("DontResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для підтвердження Вашої електронної пошти перейдіть за посиланням:.
        /// </summary>
        public static string ForConfirm {
            get {
                return ResourceManager.GetString("ForConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створюючи завдання на сайті, немає необхідності шукати виконавця самостійно - за рахунок системи миттєвих повідомлень всі фахівці за профілем Вашої завдання автоматично отримають повідомлення і відгукнуться на нього. Залишиться лише вибрати гідного..
        /// </summary>
        public static string ForCustomer {
            get {
                return ResourceManager.GetString("ForCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Якщо ви Виконавець - оформите в своєму кабінеті підписки на цікаві Вам категорії завдань. Немає необхідності шукати завдання - повідомлення надсилаються автоматично, відгукуйтеся на запити, отримуйте роботу..
        /// </summary>
        public static string ForExecutor {
            get {
                return ResourceManager.GetString("ForExecutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увійдіть в свій кабінет, заповніть інформацію і отримаєте всі переваги цього ресурсу..
        /// </summary>
        public static string GoToParlour {
            get {
                return ResourceManager.GetString("GoToParlour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підтвердити реєстрацію →.
        /// </summary>
        public static string LnkConfirm {
            get {
                return ResourceManager.GetString("LnkConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стаття на сайті →.
        /// </summary>
        public static string LnkNewsOnSite {
            get {
                return ResourceManager.GetString("LnkNewsOnSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відмовитися від розсилки новин.
        /// </summary>
        public static string LnkNewsUnsubscribe {
            get {
                return ResourceManager.GetString("LnkNewsUnsubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я хочу встановити доступ →.
        /// </summary>
        public static string LnkRecovery {
            get {
                return ResourceManager.GetString("LnkRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перейти до мого кабінету →.
        /// </summary>
        public static string LnkToParlour {
            get {
                return ResourceManager.GetString("LnkToParlour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перейти до завдання →.
        /// </summary>
        public static string LnkToTask {
            get {
                return ResourceManager.GetString("LnkToTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відмовитися від реєстрації.
        /// </summary>
        public static string LnkUnsubscribe {
            get {
                return ResourceManager.GetString("LnkUnsubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to більше 50 000 учасників.
        /// </summary>
        public static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зв&apos;язок з техподдержкой.
        /// </summary>
        public static string ModerEmail {
            get {
                return ResourceManager.GetString("ModerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви отримали цей лист так як зареєстровані на сайті Avelango.com і підписані на розсилку новин..
        /// </summary>
        public static string NewsLetter {
            get {
                return ResourceManager.GetString("NewsLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новини від Avelango.com.
        /// </summary>
        public static string NewsMail {
            get {
                return ResourceManager.GetString("NewsMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Якщо Ви не хочете отримувати новини - відпишіть, натиснувши на відповідне посилання нижче..
        /// </summary>
        public static string NewsUnsubscribe {
            get {
                return ResourceManager.GetString("NewsUnsubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NewTask {
            get {
                return ResourceManager.GetString("NewTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для Вас нове завдання на Avelango.com.
        /// </summary>
        public static string NewTaskMail {
            get {
                return ResourceManager.GetString("NewTaskMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви отримали цей лист так як зареєстровані на сайті Avelango.com і підписані на розсилку повідомлень по обраних категоріях..
        /// </summary>
        public static string NewTaskSending {
            get {
                return ResourceManager.GetString("NewTaskSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Якщо Ви не хочете отримувати розсилку - змініть настроювання, увійшовши до свого облікового запису в пункт меню &quot;Групи та передплати&quot;..
        /// </summary>
        public static string NewTaskUnsubscribe {
            get {
                return ResourceManager.GetString("NewTaskUnsubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to миттєві повідомлення.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500 нових замовлень щодня.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Це можливість створювати завдання і тут же отримувати пропозиції від виконавців або виконувати завдання, заробляючи гроші..
        /// </summary>
        public static string Possibility {
            get {
                return ResourceManager.GetString("Possibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Recovery {
            get {
                return ResourceManager.GetString("Recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Якщо Ви не робили цього - ігноруйте цей лист.
        /// </summary>
        public static string RecoveryIgnore {
            get {
                return ResourceManager.GetString("RecoveryIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відновлення доступу до Avelango.com.
        /// </summary>
        public static string RecoveryMail {
            get {
                return ResourceManager.GetString("RecoveryMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для відновлення доступу до свого облікового запису - по перейдіть посиланню нижче.
        /// </summary>
        public static string RecoveryMessage {
            get {
                return ResourceManager.GetString("RecoveryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви отримали цей лист так як виконали запит на відновлення пароля на сайті Avelango.com.
        /// </summary>
        public static string RecoveryRequest {
            get {
                return ResourceManager.GetString("RecoveryRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реєстрація.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увійти через соціальну мережу.
        /// </summary>
        public static string Social {
            get {
                return ResourceManager.GetString("Social", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Можливість входу через соціальні мережі відсутня.
        /// </summary>
        public static string SocialDisable {
            get {
                return ResourceManager.GetString("SocialDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реєстрація на сайті пройшла успішно.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TaskResponse {
            get {
                return ResourceManager.GetString("TaskResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прийшов відгук від виконавця на Avelango.com.
        /// </summary>
        public static string TaskResponseMail {
            get {
                return ResourceManager.GetString("TaskResponseMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Якщо Ви цього не робили - відмовтеся, натиснувши на відповідне посилання нижче.
        /// </summary>
        public static string Unsubscribe {
            get {
                return ResourceManager.GetString("Unsubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повідомлення від Avelango.com.
        /// </summary>
        public static string WarningMail {
            get {
                return ResourceManager.GetString("WarningMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ласкаво просимо на Avelango.com.
        /// </summary>
        public static string Wellcome {
            get {
                return ResourceManager.GetString("Wellcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви отримали цей лист так як зареєструвалися на сайті Avelango.com.
        /// </summary>
        public static string YouReceive {
            get {
                return ResourceManager.GetString("YouReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заощаджуй свій час.
        /// </summary>
        public static string YourTime {
            get {
                return ResourceManager.GetString("YourTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви отримали цей лист так як були зареєстровані на сайті Avelango.com..
        /// </summary>
        public static string YouWasReceived {
            get {
                return ResourceManager.GetString("YouWasReceived", resourceCulture);
            }
        }
    }
}
