//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Avelango.Models.Orm;

namespace Avelango.DbOrm
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AvelangoDbEntities : DbContext
    {
        public AvelangoDbEntities()
            : base("name=AvelangoDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChatMessages> ChatMessages { get; set; }
        public virtual DbSet<Chats> Chats { get; set; }
        public virtual DbSet<CommonAdvertising> CommonAdvertising { get; set; }
        public virtual DbSet<CommonNews> CommonNews { get; set; }
        public virtual DbSet<Events> Events { get; set; }
        public virtual DbSet<Mails> Mails { get; set; }
        public virtual DbSet<Notifications> Notifications { get; set; }
        public virtual DbSet<PortfolioJobImages> PortfolioJobImages { get; set; }
        public virtual DbSet<PortfolioJobs> PortfolioJobs { get; set; }
        public virtual DbSet<Portfolios> Portfolios { get; set; }
        public virtual DbSet<RialtoAction> RialtoAction { get; set; }
        public virtual DbSet<RialtoChat> RialtoChat { get; set; }
        public virtual DbSet<RialtoState> RialtoState { get; set; }
        public virtual DbSet<RialtoUserAssets> RialtoUserAssets { get; set; }
        public virtual DbSet<RialtoUsersStates> RialtoUsersStates { get; set; }
        public virtual DbSet<SmsSending> SmsSending { get; set; }
        public virtual DbSet<TaskAttachments> TaskAttachments { get; set; }
        public virtual DbSet<TaskBids> TaskBids { get; set; }
        public virtual DbSet<TaskOffers> TaskOffers { get; set; }
        public virtual DbSet<TaskPreWorkers> TaskPreWorkers { get; set; }
        public virtual DbSet<Tasks> Tasks { get; set; }
        public virtual DbSet<TempUserData> TempUserData { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
