//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avelango.Resources.Email.Ru {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Content {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Content() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Avelango.Resources.Email.Ru.Content", typeof(Content).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обзор исполнителей.
        /// </summary>
        public static string BtnAllExecutors {
            get {
                return ResourceManager.GetString("BtnAllExecutors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обзор заданий.
        /// </summary>
        public static string BtnAllTasks {
            get {
                return ResourceManager.GetString("BtnAllTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Узнать больше.
        /// </summary>
        public static string BtnLearnMore {
            get {
                return ResourceManager.GetString("BtnLearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш аккаунт на сайте деактивирован.
        /// </summary>
        public static string DeactHeader {
            get {
                return ResourceManager.GetString("DeactHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Deactivation {
            get {
                return ResourceManager.GetString("Deactivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Деактивация на Avelango.com.
        /// </summary>
        public static string DeactMail {
            get {
                return ResourceManager.GetString("DeactMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ознакомиться с правилами сайта.
        /// </summary>
        public static string DeactMessage {
            get {
                return ResourceManager.GetString("DeactMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Деактивация - блокировка возможности использовать свой аккаунт. При этом Ваши данные не удаляются..
        /// </summary>
        public static string DeactNote {
            get {
                return ResourceManager.GetString("DeactNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш аккаунт на сайте удален.
        /// </summary>
        public static string DeleteHeader {
            get {
                return ResourceManager.GetString("DeleteHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление аккаунта на Avelango.com.
        /// </summary>
        public static string DeleteMail {
            get {
                return ResourceManager.GetString("DeleteMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Правила сайта.
        /// </summary>
        public static string DeleteMessage {
            get {
                return ResourceManager.GetString("DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Удаление аккаунта - удаление данных вашей учетной записи без возможности их восстановления..
        /// </summary>
        public static string DeleteNote {
            get {
                return ResourceManager.GetString("DeleteNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Это письмо отправлено автоматически, на него не нужно отвечать..
        /// </summary>
        public static string DontResponse {
            get {
                return ResourceManager.GetString("DontResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для подтверждения Вашего e-mail перейдите по ссылке:.
        /// </summary>
        public static string ForConfirm {
            get {
                return ResourceManager.GetString("ForConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создавая задание на сайте, нет необходимости искать исполнителя самостоятельно - за счет системы мгновенных уведомлений все специалисты по профилю Вашего задания автоматически получат сообщения и откликнутся на него. Останется лишь выбрать достойного..
        /// </summary>
        public static string ForCustomer {
            get {
                return ResourceManager.GetString("ForCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если вы Исполнитель - оформите в своем кабинете подписки на интересные Вам категории заданий. Нет необходимости искать задания - уведомления присылаются автоматически, откликайтесь на запросы, получайте работу..
        /// </summary>
        public static string ForExecutor {
            get {
                return ResourceManager.GetString("ForExecutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войдите в свой кабинет, заполните информацию и получите все преимущества этого ресурса..
        /// </summary>
        public static string GoToParlour {
            get {
                return ResourceManager.GetString("GoToParlour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердить регистрацию →.
        /// </summary>
        public static string LnkConfirm {
            get {
                return ResourceManager.GetString("LnkConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статья на сайте →.
        /// </summary>
        public static string LnkNewsOnSite {
            get {
                return ResourceManager.GetString("LnkNewsOnSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отписаться от рассылки новостей.
        /// </summary>
        public static string LnkNewsUnsubscribe {
            get {
                return ResourceManager.GetString("LnkNewsUnsubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я хочу воостановить доступ →.
        /// </summary>
        public static string LnkRecovery {
            get {
                return ResourceManager.GetString("LnkRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перейти в мой кабинет →.
        /// </summary>
        public static string LnkToParlour {
            get {
                return ResourceManager.GetString("LnkToParlour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перейти к заданию →.
        /// </summary>
        public static string LnkToTask {
            get {
                return ResourceManager.GetString("LnkToTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отказаться от регистрации.
        /// </summary>
        public static string LnkUnsubscribe {
            get {
                return ResourceManager.GetString("LnkUnsubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to больше 50 000 участников.
        /// </summary>
        public static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Связь с техподдержкой.
        /// </summary>
        public static string ModerEmail {
            get {
                return ResourceManager.GetString("ModerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы получили данное письмо так как зарегистрированы на сайте Avelango.com и подписаны на рассылку новостей..
        /// </summary>
        public static string NewsLetter {
            get {
                return ResourceManager.GetString("NewsLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новости от Avelango.com.
        /// </summary>
        public static string NewsMail {
            get {
                return ResourceManager.GetString("NewsMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если Вы не хотите получать новости - отпишитесь, нажав на соответствующую ссылку ниже..
        /// </summary>
        public static string NewsUnsubscribe {
            get {
                return ResourceManager.GetString("NewsUnsubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NewTask {
            get {
                return ResourceManager.GetString("NewTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для Вас новое задание на Avelango.com.
        /// </summary>
        public static string NewTaskMail {
            get {
                return ResourceManager.GetString("NewTaskMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы получили данное письмо так как зарегистрированы на сайте Avelango.com и подписаны на рассылку сообщений по выбранным категориям..
        /// </summary>
        public static string NewTaskSending {
            get {
                return ResourceManager.GetString("NewTaskSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если Вы не хотите получать рассылку - измените настройки, войдя в свой аккаунт в пункт меню &quot;Группы и подписки&quot;..
        /// </summary>
        public static string NewTaskUnsubscribe {
            get {
                return ResourceManager.GetString("NewTaskUnsubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to мгновенные уведомления.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500 новых заказов ежедневно.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Это возможность создавать задания и тут же получать предложения от исполнителей или выполнять задания, зарабатывая деньги..
        /// </summary>
        public static string Possibility {
            get {
                return ResourceManager.GetString("Possibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Recovery {
            get {
                return ResourceManager.GetString("Recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если Вы не делали этого - проигнорируте данное письмо.
        /// </summary>
        public static string RecoveryIgnore {
            get {
                return ResourceManager.GetString("RecoveryIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Восстановление доступа к Avelango.com.
        /// </summary>
        public static string RecoveryMail {
            get {
                return ResourceManager.GetString("RecoveryMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для восстановления доступа к своему аккаунту - перейдите по ссылке ниже.
        /// </summary>
        public static string RecoveryMessage {
            get {
                return ResourceManager.GetString("RecoveryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы получили это письмо так как выполнили запрос на восстановление пароля на сайте Avelango.com.
        /// </summary>
        public static string RecoveryRequest {
            get {
                return ResourceManager.GetString("RecoveryRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти через социальную сеть.
        /// </summary>
        public static string Social {
            get {
                return ResourceManager.GetString("Social", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возможность входа через социальные сети отсутствует.
        /// </summary>
        public static string SocialDisable {
            get {
                return ResourceManager.GetString("SocialDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация на сайте прошла успешно.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TaskResponse {
            get {
                return ResourceManager.GetString("TaskResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пришел отклик от исполнителя на Avelango.com.
        /// </summary>
        public static string TaskResponseMail {
            get {
                return ResourceManager.GetString("TaskResponseMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если Вы этого не делали - откажитесь, нажав на соответствующую ссылку ниже.
        /// </summary>
        public static string Unsubscribe {
            get {
                return ResourceManager.GetString("Unsubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уведомление от Avelango.com.
        /// </summary>
        public static string WarningMail {
            get {
                return ResourceManager.GetString("WarningMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добро пожаловать на Avelango.com.
        /// </summary>
        public static string Wellcome {
            get {
                return ResourceManager.GetString("Wellcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы получили данное письмо так как зарегистрировались на сайте Avelango.com.
        /// </summary>
        public static string YouReceive {
            get {
                return ResourceManager.GetString("YouReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экономь свое время.
        /// </summary>
        public static string YourTime {
            get {
                return ResourceManager.GetString("YourTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы получили данное письмо так как были зарегистрированы на сайте Avelango.com..
        /// </summary>
        public static string YouWasReceived {
            get {
                return ResourceManager.GetString("YouWasReceived", resourceCulture);
            }
        }
    }
}
