//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avelango.Resources.Pages.Ua {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Layout {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Layout() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Avelango.Resources.Pages.Ua.Layout", typeof(Layout).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Про нас.
        /// </summary>
        public static string ABOUTUS {
            get {
                return ResourceManager.GetString("ABOUTUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Угода з користувачем.
        /// </summary>
        public static string AGREEMENT {
            get {
                return ResourceManager.GetString("AGREEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вхід.
        /// </summary>
        public static string BTNENTER {
            get {
                return ResourceManager.GetString("BTNENTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виконавці.
        /// </summary>
        public static string BTNEXECUTORS {
            get {
                return ResourceManager.GetString("BTNEXECUTORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вихід.
        /// </summary>
        public static string BTNEXIT {
            get {
                return ResourceManager.GetString("BTNEXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Замовлення.
        /// </summary>
        public static string BTNORDERS {
            get {
                return ResourceManager.GetString("BTNORDERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакти.
        /// </summary>
        public static string CONTACTS {
            get {
                return ResourceManager.GetString("CONTACTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Правила сайту.
        /// </summary>
        public static string RULES {
            get {
                return ResourceManager.GetString("RULES", resourceCulture);
            }
        }
    }
}
