//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avelango.Resources.Pages.Ua {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class User {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal User() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Avelango.Resources.Pages.Ua.User", typeof(User).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Про мене:.
        /// </summary>
        public static string ABOUTME {
            get {
                return ResourceManager.GetString("ABOUTME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дії.
        /// </summary>
        public static string ACTIONS {
            get {
                return ResourceManager.GetString("ACTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати картинку.
        /// </summary>
        public static string ADDIMAGE {
            get {
                return ResourceManager.GetString("ADDIMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Баланс.
        /// </summary>
        public static string BALAN {
            get {
                return ResourceManager.GetString("BALAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата народження.
        /// </summary>
        public static string BIRTHDAY {
            get {
                return ResourceManager.GetString("BIRTHDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати роботу в портфоліо.
        /// </summary>
        public static string BTNADDJOBTOPORTFO {
            get {
                return ResourceManager.GetString("BTNADDJOBTOPORTFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відмінити.
        /// </summary>
        public static string BTNCANCEL {
            get {
                return ResourceManager.GetString("BTNCANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Змінити пароль.
        /// </summary>
        public static string BTNCHPASS {
            get {
                return ResourceManager.GetString("BTNCHPASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створити завдання.
        /// </summary>
        public static string BTNCREATEORDER {
            get {
                return ResourceManager.GetString("BTNCREATEORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зберегти зміни.
        /// </summary>
        public static string BTNSAVE {
            get {
                return ResourceManager.GetString("BTNSAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Країна, місто.
        /// </summary>
        public static string COUNTCITY {
            get {
                return ResourceManager.GetString("COUNTCITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ім&apos;я замовника.
        /// </summary>
        public static string CUSTOMERNAME {
            get {
                return ResourceManager.GetString("CUSTOMERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        public static string DATE {
            get {
                return ResourceManager.GetString("DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EMAIL {
            get {
                return ResourceManager.GetString("EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail розсилка.
        /// </summary>
        public static string EMAILDELIV {
            get {
                return ResourceManager.GetString("EMAILDELIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ім&apos;я виконавця.
        /// </summary>
        public static string EXECUTORNAME {
            get {
                return ResourceManager.GetString("EXECUTORNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата завершення.
        /// </summary>
        public static string EXPIRDAY {
            get {
                return ResourceManager.GetString("EXPIRDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По батькові.
        /// </summary>
        public static string FATHNAME {
            get {
                return ResourceManager.GetString("FATHNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жіночий.
        /// </summary>
        public static string FEMALE {
            get {
                return ResourceManager.GetString("FEMALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фото.
        /// </summary>
        public static string FOTO {
            get {
                return ResourceManager.GetString("FOTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я Замовник.
        /// </summary>
        public static string ICUSTOM {
            get {
                return ResourceManager.GetString("ICUSTOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я Виконавець.
        /// </summary>
        public static string IEXEC {
            get {
                return ResourceManager.GetString("IEXEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чоловік.
        /// </summary>
        public static string MALE {
            get {
                return ResourceManager.GetString("MALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мітка.
        /// </summary>
        public static string MARK {
            get {
                return ResourceManager.GetString("MARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Іспити.
        /// </summary>
        public static string MNEXAM {
            get {
                return ResourceManager.GetString("MNEXAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вибране.
        /// </summary>
        public static string MNFAVOR {
            get {
                return ResourceManager.GetString("MNFAVOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нагороди.
        /// </summary>
        public static string MNHONOR {
            get {
                return ResourceManager.GetString("MNHONOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повідомлення.
        /// </summary>
        public static string MNMESSAG {
            get {
                return ResourceManager.GetString("MNMESSAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мої гроші.
        /// </summary>
        public static string MNMONEY {
            get {
                return ResourceManager.GetString("MNMONEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мої замовлення.
        /// </summary>
        public static string MNMYORD {
            get {
                return ResourceManager.GetString("MNMYORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мої праці.
        /// </summary>
        public static string MNMYWOR {
            get {
                return ResourceManager.GetString("MNMYWOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Особисті дані.
        /// </summary>
        public static string MNPERSDATA {
            get {
                return ResourceManager.GetString("MNPERSDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Портфоліо.
        /// </summary>
        public static string MNPORTFO {
            get {
                return ResourceManager.GetString("MNPORTFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відгуки.
        /// </summary>
        public static string MNREVIEW {
            get {
                return ResourceManager.GetString("MNREVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Групи і підписки.
        /// </summary>
        public static string MNSUBSCR {
            get {
                return ResourceManager.GetString("MNSUBSCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моя сторінка на сайті.
        /// </summary>
        public static string MYPAGE {
            get {
                return ResourceManager.GetString("MYPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ім&apos;я.
        /// </summary>
        public static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нова інформація на сайті.
        /// </summary>
        public static string NEWSITEINFO {
            get {
                return ResourceManager.GetString("NEWSITEINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Місто.
        /// </summary>
        public static string PHCITY {
            get {
                return ResourceManager.GetString("PHCITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Країна.
        /// </summary>
        public static string PHCOUNT {
            get {
                return ResourceManager.GetString("PHCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть адресу електронної пошти.
        /// </summary>
        public static string PHEMAIL {
            get {
                return ResourceManager.GetString("PHEMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть батькові.
        /// </summary>
        public static string PHFATHNAME {
            get {
                return ResourceManager.GetString("PHFATHNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовок.
        /// </summary>
        public static string PHHEADER {
            get {
                return ResourceManager.GetString("PHHEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Короткий опис роботи (до 500 символів).
        /// </summary>
        public static string PHJOBDESCRIPT {
            get {
                return ResourceManager.GetString("PHJOBDESCRIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва роботи.
        /// </summary>
        public static string PHJOBTITLE {
            get {
                return ResourceManager.GetString("PHJOBTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть ім&apos;я.
        /// </summary>
        public static string PHNAME {
            get {
                return ResourceManager.GetString("PHNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        public static string PHONE {
            get {
                return ResourceManager.GetString("PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть номер телефону 1.
        /// </summary>
        public static string PHPHONE1 {
            get {
                return ResourceManager.GetString("PHPHONE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть номер телефону 2.
        /// </summary>
        public static string PHPHONE2 {
            get {
                return ResourceManager.GetString("PHPHONE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть номер телефону 3.
        /// </summary>
        public static string PHPHONE3 {
            get {
                return ResourceManager.GetString("PHPHONE3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть Skype.
        /// </summary>
        public static string PHSKYPE {
            get {
                return ResourceManager.GetString("PHSKYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть прізвище.
        /// </summary>
        public static string PHSURNAME {
            get {
                return ResourceManager.GetString("PHSURNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push повідомлення.
        /// </summary>
        public static string PUSHNOTIF {
            get {
                return ResourceManager.GetString("PUSHNOTIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рейтинг.
        /// </summary>
        public static string RATING {
            get {
                return ResourceManager.GetString("RATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На сайті.
        /// </summary>
        public static string REGFROM {
            get {
                return ResourceManager.GetString("REGFROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виберіть групи:.
        /// </summary>
        public static string SELECTGROUPS {
            get {
                return ResourceManager.GetString("SELECTGROUPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підлога.
        /// </summary>
        public static string SEX {
            get {
                return ResourceManager.GetString("SEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype.
        /// </summary>
        public static string SKYPE {
            get {
                return ResourceManager.GetString("SKYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS розсилка.
        /// </summary>
        public static string SMSDELIV {
            get {
                return ResourceManager.GetString("SMSDELIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата початку.
        /// </summary>
        public static string STARTDAY {
            get {
                return ResourceManager.GetString("STARTDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        public static string STATUS {
            get {
                return ResourceManager.GetString("STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підписатися на розсилку по обраних групах:.
        /// </summary>
        public static string SUBSCRIBE {
            get {
                return ResourceManager.GetString("SUBSCRIBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сума.
        /// </summary>
        public static string SUMM {
            get {
                return ResourceManager.GetString("SUMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прізвище.
        /// </summary>
        public static string SURNAME {
            get {
                return ResourceManager.GetString("SURNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст завдання.
        /// </summary>
        public static string TASKCONTENT {
            get {
                return ResourceManager.GetString("TASKCONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Час.
        /// </summary>
        public static string TIME {
            get {
                return ResourceManager.GetString("TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Транзакція.
        /// </summary>
        public static string TRANSACTION {
            get {
                return ResourceManager.GetString("TRANSACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ласкаво просимо до кабінету.
        /// </summary>
        public static string WELLCOMETOACC {
            get {
                return ResourceManager.GetString("WELLCOMETOACC", resourceCulture);
            }
        }
    }
}
