//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avelango.Resources.Notifications.Ru {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NotifyContext {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotifyContext() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Avelango.Resources.Notifications.Ru.NotifyContext", typeof(NotifyContext).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вас выбрали исполнителем задания.
        /// </summary>
        public static string CUSTOMERCHOSENTHEWORKERSTEXT {
            get {
                return ResourceManager.GetString("CUSTOMERCHOSENTHEWORKERSTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новое задание ожидает модерации.
        /// </summary>
        public static string NEWTASKTEXT {
            get {
                return ResourceManager.GetString("NEWTASKTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to откликнулся на задание.
        /// </summary>
        public static string TASKBIDDEDTEXT {
            get {
                return ResourceManager.GetString("TASKBIDDEDTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый отклик.
        /// </summary>
        public static string TASKBIDDEDTITLE {
            get {
                return ResourceManager.GetString("TASKBIDDEDTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заказчик завершил задание.
        /// </summary>
        public static string TASKCOMPLETEDBYCUSTOMERTEXT {
            get {
                return ResourceManager.GetString("TASKCOMPLETEDBYCUSTOMERTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исполнитель завершил задание.
        /// </summary>
        public static string TASKCOMPLETEDBYWORKERTEXT {
            get {
                return ResourceManager.GetString("TASKCOMPLETEDBYWORKERTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поздравляем! Ваше задание отмодерировано и доступно пользователям..
        /// </summary>
        public static string TASKCONFIRMEDTEXT {
            get {
                return ResourceManager.GetString("TASKCONFIRMEDTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to К сожалению, задание не прошло модерацию :(.
        /// </summary>
        public static string TASKDISMISSEDTEXT {
            get {
                return ResourceManager.GetString("TASKDISMISSEDTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to передумал выполнять задание.
        /// </summary>
        public static string TASKUNBIDDEDTEXT {
            get {
                return ResourceManager.GetString("TASKUNBIDDEDTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отклик удален.
        /// </summary>
        public static string TASKUNBIDDEDTITLE {
            get {
                return ResourceManager.GetString("TASKUNBIDDEDTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приступил выполнять задание .
        /// </summary>
        public static string WORKERSTARTEDTASKTEXT {
            get {
                return ResourceManager.GetString("WORKERSTARTEDTASKTEXT", resourceCulture);
            }
        }
    }
}
