//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avelango.Resources.Email.En {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Content {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Content() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Avelango.Resources.Email.En.Content", typeof(Content).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse executors.
        /// </summary>
        public static string BtnAllExecutors {
            get {
                return ResourceManager.GetString("BtnAllExecutors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks overview.
        /// </summary>
        public static string BtnAllTasks {
            get {
                return ResourceManager.GetString("BtnAllTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To learn more.
        /// </summary>
        public static string BtnLearnMore {
            get {
                return ResourceManager.GetString("BtnLearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account on the site disabled.
        /// </summary>
        public static string DeactHeader {
            get {
                return ResourceManager.GetString("DeactHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Deactivation {
            get {
                return ResourceManager.GetString("Deactivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivation on Avelango.com.
        /// </summary>
        public static string DeactMail {
            get {
                return ResourceManager.GetString("DeactMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read the site rules.
        /// </summary>
        public static string DeactMessage {
            get {
                return ResourceManager.GetString("DeactMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Deactivation - blocking the ability to use your account. In this case your data will not be deleted..
        /// </summary>
        public static string DeactNote {
            get {
                return ResourceManager.GetString("DeactNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account on the site deleted.
        /// </summary>
        public static string DeleteHeader {
            get {
                return ResourceManager.GetString("DeleteHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting your account on Avelango.com.
        /// </summary>
        public static string DeleteMail {
            get {
                return ResourceManager.GetString("DeleteMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site rules.
        /// </summary>
        public static string DeleteMessage {
            get {
                return ResourceManager.GetString("DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Delete Account - Delete your account data without the possibility of recovery..
        /// </summary>
        public static string DeleteNote {
            get {
                return ResourceManager.GetString("DeleteNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email was sent automatically, it is not necessary to answer..
        /// </summary>
        public static string DontResponse {
            get {
                return ResourceManager.GetString("DontResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To confirm your e-mail, go to:.
        /// </summary>
        public static string ForConfirm {
            get {
                return ResourceManager.GetString("ForConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a job site, there is no need to search for executors yourself - due to instant notifications all experts on the profile of your job will automatically receive the message and respond to it. Will only choose a worthy..
        /// </summary>
        public static string ForCustomer {
            get {
                return ResourceManager.GetString("ForCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you Executor - make in your account subscription to job categories interest you. No need to look for jobs - notifications are sent automatically to respond to requests, get a job..
        /// </summary>
        public static string ForExecutor {
            get {
                return ResourceManager.GetString("ForExecutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in to your account, fill out the information and get all the benefits of this resource..
        /// </summary>
        public static string GoToParlour {
            get {
                return ResourceManager.GetString("GoToParlour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm registration →.
        /// </summary>
        public static string LnkConfirm {
            get {
                return ResourceManager.GetString("LnkConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article online →.
        /// </summary>
        public static string LnkNewsOnSite {
            get {
                return ResourceManager.GetString("LnkNewsOnSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscribe from our newsletter.
        /// </summary>
        public static string LnkNewsUnsubscribe {
            get {
                return ResourceManager.GetString("LnkNewsUnsubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want to restore access →.
        /// </summary>
        public static string LnkRecovery {
            get {
                return ResourceManager.GetString("LnkRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to my account →.
        /// </summary>
        public static string LnkToParlour {
            get {
                return ResourceManager.GetString("LnkToParlour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the task →.
        /// </summary>
        public static string LnkToTask {
            get {
                return ResourceManager.GetString("LnkToTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refuse registration.
        /// </summary>
        public static string LnkUnsubscribe {
            get {
                return ResourceManager.GetString("LnkUnsubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more than 50 000 participants.
        /// </summary>
        public static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Tech Support.
        /// </summary>
        public static string ModerEmail {
            get {
                return ResourceManager.GetString("ModerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You received this email because was registered on the website Avelango.com and subscribed to the newsletter..
        /// </summary>
        public static string NewsLetter {
            get {
                return ResourceManager.GetString("NewsLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News from Avelango.com.
        /// </summary>
        public static string NewsMail {
            get {
                return ResourceManager.GetString("NewsMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you do not want to receive the newsletter - unsubscribe by clicking on the appropriate link below..
        /// </summary>
        public static string NewsUnsubscribe {
            get {
                return ResourceManager.GetString("NewsUnsubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NewTask {
            get {
                return ResourceManager.GetString("NewTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New task for you on Avelango.com.
        /// </summary>
        public static string NewTaskMail {
            get {
                return ResourceManager.GetString("NewTaskMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You received this email because was registered on the website Avelango.com and subscribed to the newsletter messages in selected categories..
        /// </summary>
        public static string NewTaskSending {
            get {
                return ResourceManager.GetString("NewTaskSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you do not want to receive the newsletter - change the settings by logging in to your account in the &quot;Groups and Subscriptions&quot; menu..
        /// </summary>
        public static string NewTaskUnsubscribe {
            get {
                return ResourceManager.GetString("NewTaskUnsubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to instant notifications.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500 new tasks every day.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an opportunity to create jobs and immediately receive offers from executors or perform tasks, earning money..
        /// </summary>
        public static string Possibility {
            get {
                return ResourceManager.GetString("Possibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Recovery {
            get {
                return ResourceManager.GetString("Recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you do not do this – ignore this letter .
        /// </summary>
        public static string RecoveryIgnore {
            get {
                return ResourceManager.GetString("RecoveryIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring access to Avelango.com.
        /// </summary>
        public static string RecoveryMail {
            get {
                return ResourceManager.GetString("RecoveryMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To regain access to your account - click the link below.
        /// </summary>
        public static string RecoveryMessage {
            get {
                return ResourceManager.GetString("RecoveryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You received this message because the completed request for password recovery on the site Avelango.com.
        /// </summary>
        public static string RecoveryRequest {
            get {
                return ResourceManager.GetString("RecoveryRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check in.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in with a social network.
        /// </summary>
        public static string Social {
            get {
                return ResourceManager.GetString("Social", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ability to log in via the social network does not.
        /// </summary>
        public static string SocialDisable {
            get {
                return ResourceManager.GetString("SocialDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration on the site is successful.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TaskResponse {
            get {
                return ResourceManager.GetString("TaskResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Came the response from the Executive on Avelango.com.
        /// </summary>
        public static string TaskResponseMail {
            get {
                return ResourceManager.GetString("TaskResponseMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you did not do - give up by clicking on the link below.
        /// </summary>
        public static string Unsubscribe {
            get {
                return ResourceManager.GetString("Unsubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification of Avelango.com.
        /// </summary>
        public static string WarningMail {
            get {
                return ResourceManager.GetString("WarningMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Avelango.com.
        /// </summary>
        public static string Wellcome {
            get {
                return ResourceManager.GetString("Wellcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have received this email as it registered on the site Avelango.com.
        /// </summary>
        public static string YouReceive {
            get {
                return ResourceManager.GetString("YouReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save your time.
        /// </summary>
        public static string YourTime {
            get {
                return ResourceManager.GetString("YourTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You received this email because have been registered on the website Avelango.com..
        /// </summary>
        public static string YouWasReceived {
            get {
                return ResourceManager.GetString("YouWasReceived", resourceCulture);
            }
        }
    }
}
